### PR TITLE
WIP Support multiple Alertmanager versions

### LINKED ISSUE #34: Support multiple Alertmanager versions
We can make unsee support multiple versions by first checking remote Alertmanager version via `GET /api/v1/status`, reading the version and using the correct model for response handling.

### PR DESCRIPTION
**Pull request by prymitive**
This is trying to fix #34, this branch is based on top of #35 
Passes all tests and organic testing, but need to add more integration tests and ability to load mock locally in `make run`.

### CODE REVIEW

**Comment by mattbostock** [comment]
I don't think we need to support multiple versions at once - it adds complexity without adding much value.

**Comment by prymitive** [comment]
I don't think we need to support multiple, but we probably gonna need to support current and current-1 version, to ease with upgrades and testing new versions. In the end Alertmanager gives us same data, just formatted differently, so there isn't any huge complexity involved, everything version specific happens inside `alertmanager` package, plus this PR refactors the code to make a cleaner separation between Alertmanager data model and what unsee uses internally, so all unsee code except `alertmanager` package doesn't need to know anything about Alertmanager data model. Having single tree that can handle everything will also simplify releases, as we don't need to keep multiple release branches alive and backport fixes there.
This is still just first batch of code and I will try to simplify it more.

**Comment by mattbostock** [comment]
There are changes to 50 files in this PR - that seems like a lot of overheard to me.

I'd rather use release branches (and backport fixes if necessary). Though Alertmanager's API is still unstable, so I think we should expect that users will be closing tracking the latest releases.

The code refactorings to tidy up interfaces should be moved into a separate PR.

**Comment by prymitive** [comment]
Closing, will follow up on another PR

**Pull request closed without merging**
