### PR TITLE
Fix autocomplete dropdown selection color

### PR DESCRIPTION
**Pull request by prymitive**
Selector is too wide and doesn't action, add `div` to make it work again.

### CODE REVIEW

**Comment by terinjokes** [comment]
What does this change have to do with the selection color?

**Comment by prymitive** [comment]
Those selectors have styling changes applied for autocomplete dropdown, making it look like the rest of bootstrap flatly themed elements. There's no less or scss in https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/tree/master/src that could read of flatly variables file.

**Comment by prymitive** [comment]
Classes are controlled by typeahead, not by tagsinpt, so I need to follow  https://github.com/corejavascript/typeahead.js/blob/master/doc/jquery_typeahead.md#class-names and configure proper classes here.

**Comment by prymitive** [comment]
Reworked to use a less style file that imports from bootstrap, see commit for details.

**Pull request merged**
