### PR TITLE
Fixes for 0.5.1

### PR DESCRIPTION
**Pull request by tcolgate**
Attempting to run unsee against Alertmanager 0.5.1 failed due to various json unsmarshaling issues with silences. I needed these changes to get things working.

### CODE REVIEW

**Comment by prymitive** [comment]
We should also document which Alertmanager versions unsee supports, as the API isn't stable yet

**Comment by tcolgate** [comment]
Would you like that adding to the PR?

**Comment by prymitive** [comment]
Sure, thanks

**Comment by prymitive** [comment]
Changes look ok, but we need to cut a 0.4.x compatible branch before we can merge, will deal with this soon. Thanks!

**Pull request merged**
