### PR TITLE
Redraw alert list of user switches to unsee tab

### PR DESCRIPTION
**Pull request by prymitive**
This should limit UI artifacts when you keep unsee tab inactive (not fucused) for a long time and a browser stops refreshing content

### CODE REVIEW

**Comment by Tenzer** [comment]
According to http://caniuse.com/#feat=pagevisibility you don't need the different vendor specific prefixes.

**Comment by prymitive** [comment]
I don't see any mention on that website that vendor prefixes aren't required. It only shows which browsers are supporting it. I think I trust mozilla docs more, demos for it, like https://github.com/samdutton/simpl/blob/gh-pages/pagevisibility/js/main.js linked from https://www.chromestatus.com/feature/5689697795833856 still uses all checks. I'd rather use mozilla example for now.

**Comment by prymitive** [comment]
Well, [spec](https://www.w3.org/TR/page-visibility/#sec-vendor-prefix) for it indicate that's those shouldn't be needed, and if browser implemented the spec than it shouldn't be required. Still, I'd rather rely on mozilla docs.

**Comment by Tenzer** [comment]
If you click the "Show all" button on the page you can see the previous versions of the browsers, they had small remarks saying that it only worked with vendor prefixes but they are no longer there. Here are the latest versions of Firefox, Chrome and Opera to require vendor prefixes for instance:
screen shot 2017-07-06 at 17 04 39
screen shot 2017-07-06 at 17 04 44
screen shot 2017-07-06 at 17 04 49

The version numbers are aligned with what is mentioned on Mozilla's page, I just find Mozilla's table more difficult to read.

**Comment by prymitive** [comment]
Fair enough, updated

**Pull request merged**
