### PR TITLE
WIP: Generate docker images based on golang-alpine for debug purposes

### PR DESCRIPTION
**Pull request by sylr**
A shell comes in handy.

### CODE REVIEW

**Comment by sylr** [comment]
Automated builds using DockerfileDebug as docker file is not working at the moment ... it still uses Dockerfile.

I've open an issue: https://github.com/docker/hub-feedback/issues/1394

**Comment by prymitive** [comment]
I'm not entirely sure what's the benefit of maintaining not one but two docker files.

**Comment by sylr** [comment]
I'd like to investigate https://github.com/cloudflare/unsee/issues/235 and to do so I need a shell on the pod to validate that it is not able to resolve DNS.

**Comment by prymitive** [comment]
You can build your own image and use that for testing

**Comment by sylr** [comment]
I've done just that but I would have liked to have such an image available in the official repo.

I though others might have liked this too.

Concerning maintaining 2 Dockerfiles, well, yes ... but it's two -20 lines files, I doubt the maintaining overhead is relevant.

Anyway, it currently does not work, automated builds on hub.docker.com use Dockerfile in all cases ...

**Comment by prymitive** [comment]
I can't find any mention of `DockerfileDebug` in docker docs, seems like it's a non standard file, I don't think it's worth to add this at this point

**Pull request closed without merging**
