### PR TITLE
Switch from manul to govendor for maintaining vendor directory

### PR DESCRIPTION
**Pull request by prymitive**
Manul works great, but using git submodules creates some problems (like https://github.com/travis-ci/travis-ci/issues/5806), switch to govendor to have reproducible builds

### CODE REVIEW

**Comment by mattbostock** [comment]
Did you consider [gvt](https://github.comFiloSottile/gvt)? We're using it for other projects at Cloudflare.

**Comment by prymitive** [comment]
I did use gvt for a while but that wasn't great experience for me.
gvt is pretty much just "go get for vendor dir", which means you need to run it manually for each and every dependency (unless I'm missing something), while manul & govendor can both _manage_ that dir for me - meaning they will both detect all used deps and install it to vendor dir & both can print and remove unused dependencies. This makes removes the entire burden of maintaining of vendor dir, you just write code and run `make vendor` once you're done to apply any required changes to the vendor dir.

**Comment by prymitive** [comment]
Any chance of a review here?

**Comment by prymitive** [comment]
Glide is ok, but it's more "noisy" tool, creates config files for you to manage and so on, while govendor does the only thing I need - manage what's inside vendor dir based on the source code.

**Comment by prymitive** [comment]
Sadly pulling master will fail, manual steps are needed:
```
git pull
rm -fr vendor
git pull
```
so it's better to have this step done early

**Pull request merged**
